### ISSUE TITLE
Feature Request: It would be very nice if you could search elements by their symbol

### ISSUE THREAD

**Issue by Jocomol** [madprops/el#1]
Eg: el Mg would show magnesium.

**Comment by madprops** [comment]
Added support for symbol search like 'k' or 'K'
https://github.com/madprops/el/commit/448fbcfa066604e450cc8390694064a7b6438cc1

**Comment by Jocomol** [comment]
Thank you, I will try it as soon as I can and give you feedback.

**Comment by Jocomol** [comment]
I tried it out, very nice, thank you
